# 基础镜像
FROM redis
# author
MAINTAINER metanet

# 挂载目录
VOLUME /home/metanet/redis
# 创建目录
RUN mkdir -p /home/metanet/redis
# 指定路径
WORKDIR /home/metanet/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/metanet/redis/redis.conf
