# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER metanet

# 挂载目录
VOLUME /home/metanet/daas/user
# 创建目录
RUN mkdir -p /home/metanet/daas/user
# 指定路径
WORKDIR /home/metanet/daas/user
# 复制jar文件到路径
COPY ./jar/metanet-daas-user.jar /home/metanet/daas/user/metanet-daas-user.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","metanet-daas-user.jar"]