# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER metanet

# 挂载目录
VOLUME /home/metanet/baas/gateway
# 创建目录
RUN mkdir -p /home/metanet/baas/gateway
# 指定路径
WORKDIR /home/metanet/baas/gateway
# 复制jar文件到路径
COPY ./jar/metanet-baas-gateway.jar /home/metanet/baas/gateway/metanet-baas-gateway.jar
# 启动网关服务
ENTRYPOINT ["java","-jar","metanet-baas-gateway.jar"]