version : '3.8'
services:
  metanet-mysql:
    container_name: metanet-mysql
    image: mysql:5.7
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    command: [
          'mysqld',
          '--innodb-buffer-pool-size=80M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1'
        ]
    environment:
      MYSQL_DATABASE: 'metanet'
      MYSQL_ROOT_PASSWORD: pwd=1000
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 10
    privileged: true
  metanet-redis:
    container_name: metanet-redis
    image: redis
    build:
      context: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/home/metanet/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /home/metanet/redis/redis.conf
    privileged: true
  metanet-nacos:
    container_name: metanet-nacos
    image: nacos/nacos-server:v2.1.1
    build:
      context: ./nacos
    environment:
      - MODE=standalone
    privileged: true
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
      - ./nacos/conf/nacos-logback.xml:/home/nacos/conf/nacos-logback.xml
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    healthcheck:
      test: ["CMD-SHELL", "echo 'ruok' | curl -s telnet://localhost:8848 || exit 1"]
      retries: 10
    depends_on:
      metanet-mysql:
        condition: service_healthy
  metanet-seata:
    container_name: metanet-seata
    image: seataio/seata-server:1.6.1
    restart: unless-stopped  # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    build:
      context: ./seata
    privileged: true
    volumes:
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime"
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/timezone"
      - "./seata/conf/application.yml:/seata-server/resources/application.yml"
      - "./seata/logs:/root/logs/seata"
    env_file:
      - ./seata/conf/seata.env
    environment:
      - STORE_MODE=db
      - SEATA_IP=192.168.20.200
      - SEATA_PORT=8091
    ports:
      - "7091:7091"
      - "8091:8091"
    depends_on:
      metanet-nacos:
        condition: service_healthy
  metanet-nginx:
    container_name: metanet-nginx
    image: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/html/dist:/home/metanet/projects/metanet-ui
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - metanet-baas-gateway
    links:
      - metanet-baas-gateway
    privileged: true
  metanet-daas-admin:
    container_name: metanet-daas-admin
    build:
      context: ./metanet/daas/admin
      dockerfile: dockerfile
    ports:
      - "8701:8701"
    volumes:
      - ./metanet/daas/admin/config:/home/metanet/daas/admin/config
    depends_on:
      - metanet-mysql
    links:
      - metanet-mysql
    privileged: true
  metanet-daas-device:
    container_name: metanet-daas-device
    build:
      context: ./metanet/daas/device
      dockerfile: dockerfile
    ports:
      - "8702:8702"
    volumes:
      - ./metanet/daas/device/config:/home/metanet/daas/device/config
    depends_on:
      - metanet-mysql
    links:
      - metanet-mysql
    privileged: true
  metanet-daas-user:
    container_name: metanet-daas-user
    build:
      context: ./metanet/daas/user
      dockerfile: dockerfile
    ports:
      - "8703:8703"
    volumes:
      - ./metanet/daas/user/config:/home/metanet/daas/user/config
    depends_on:
      - metanet-mysql
    links:
      - metanet-mysql
    privileged: true
  metanet-daas-vision:
    container_name: metanet-daas-vision
    build:
      context: ./metanet/daas/vision
      dockerfile: dockerfile
    ports:
      - "8704:8704"
    volumes:
      - ./metanet/daas/vision/config:/home/metanet/daas/vision/config
    depends_on:
      - metanet-mysql
    links:
      - metanet-mysql
    privileged: true
  metanet-baas-gateway:
    container_name: metanet-baas-gateway
    build:
      context: ./metanet/baas/gateway
      dockerfile: dockerfile
    ports:
      - "8605:8605"
    volumes:
      - ./metanet/daas/admin/config:/home/metanet/daas/admin/config
    depends_on:
      - metanet-redis
    links:
      - metanet-redis
    privileged: true
  metanet-baas-auth:
    container_name: metanet-baas-auth
    build:
      context: ./metanet/baas/auth
      dockerfile: dockerfile
    ports:
      - "8602:8602"
    volumes:
      - ./metanet/baas/auth/config:/home/metanet/baas/auth/config
    depends_on:
      - metanet-redis
    links:
      - metanet-redis
    privileged: true
  metanet-baas-app:
    container_name: metanet-baas-app
    build:
      context: ./metanet/baas/app
      dockerfile: dockerfile
    ports:
      - "8601:8601"
    volumes:
      - ./metanet/baas/app/config:/home/metanet/baas/app/config
    depends_on:
      - metanet-redis
      - metanet-mysql
    links:
      - metanet-redis
      - metanet-mysql
    privileged: true
  metanet-baas-channel:
    container_name: metanet-baas-channel
    build:
      context: ./metanet/baas/channel
      dockerfile: dockerfile
    ports:
      - "8603:8603"
    volumes:
      - ./metanet/baas/channel/config:/home/metanet/baas/channel/config
    depends_on:
      - metanet-mysql
    links:
      - metanet-mysql
    privileged: true
  metanet-baas-crm:
    container_name: metanet-baas-crm
    build:
      context: ./metanet/baas/crm
      dockerfile: dockerfile
    ports:
      - "8604:8604"
    volumes:
      - ./metanet/baas/crm/config:/home/metanet/baas/crm/config
    depends_on:
      - metanet-mysql
    links:
      - metanet-mysql
    privileged: true
  metanet-baas-openapi:
    container_name: metanet-baas-openapi
    build:
      context: ./metanet/baas/openapi
      dockerfile: dockerfile
    ports:
      - "8607:8607"
    volumes:
      - ./metanet/baas/openapi/config:/home/metanet/baas/openapi/config
    volumes:
    - ./metanet/uploadPath:/home/metanet/uploadPath
    privileged: true
  metanet-baas-monitor:
    container_name: metanet-baas-monitor
    build:
      context: ./metanet/baas/monitor
      dockerfile: dockerfile
    ports:
      - "8606:8606"
    volumes:
      - ./metanet/baas/monitor/config:/home/metanet/baas/monitor/config
    privileged: true
  metanet-baas-vision:
    container_name: metanet-baas-vision
    build:
      context: ./metanet/baas/vision
      dockerfile: dockerfile
    ports:
      - "8608:8608"
    volumes:
      - ./metanet/baas/vision/config:/home/metanet/baas/vision/config
    privileged: true
  metanet-baas-gen:
    container_name: metanet-baas-gen
    build:
      context: ./metanet/baas/gen
      dockerfile: dockerfile
    ports:
      - "8609:8609"
    volumes:
      - ./metanet/baas/gen/config:/home/metanet/baas/gen/config
    depends_on:
      - metanet-mysql
    links:
      - metanet-mysql
    privileged: true
  metanet-baas-job:
    container_name: metanet-baas-job
    build:
      context: ./metanet/baas/job
      dockerfile: dockerfile
    ports:
      - "8610:8610"
    volumes:
      - ./metanet/baas/job/config:/home/metanet/baas/job/config
    depends_on:
      - metanet-mysql
    links:
      - metanet-mysql
    privileged: true
  metanet-baas-file:
    container_name: metanet-baas-file
    build:
      context: ./metanet/baas/file
      dockerfile: dockerfile
    ports:
      - "8611:8611"
    volumes:
      - ./metanet/uploadPath:/home/metanet/uploadPath
      - ./metanet/baas/file/config:/home/metanet/baas/file/config
    privileged: true
