# 基础镜像
FROM nginx
# author
MAINTAINER metanet

# 挂载目录
VOLUME /home/metanet/metanet-ui-auth
# 创建目录
RUN mkdir -p /home/metanet/metanet-ui-auth
# 指定路径
WORKDIR /home/metanet/metanet-ui-auth
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/metanet/metanet-ui-auth
