# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER metanet

# 挂载目录
VOLUME /home/metanet/baas/auth
# 创建目录
RUN mkdir -p /home/metanet/baas/auth
# 指定路径
WORKDIR /home/metanet/baas/auth
# 复制jar文件到路径
COPY ./jar/metanet-baas-auth.jar /home/metanet/baas/auth/metanet-baas-auth.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","metanet-baas-auth.jar"]