# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER metanet

# 挂载目录
VOLUME /home/metanet/baas/vision
# 创建目录
RUN mkdir -p /home/metanet/baas/vision
# 指定路径
WORKDIR /home/metanet/baas/vision
# 复制jar文件到路径
COPY ./jar/metanet-baas-vision.jar /home/metanet/baas/vision/metanet-baas-vision.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","metanet-baas-vision.jar"]